### ISSUE TITLE
Dynamic page loading failed

### ISSUE THREAD

**Issue by ariamckinley** [aweary/tinytime#1]
When including `tinytime` in my webpack project, I'm given this runtime error (happens on `import`)

![screen shot 2017-03-04 at 6 04 10 pm](https://cloud.githubusercontent.com/assets/1624279/23582956/08af4a78-0105-11e7-879c-fcff7a02b69e.png)

**Comment by aweary** [comment]
Thanks for the report @garetmckinley! I think its probably because I have [`jsnext:main` pointing to  `src`](https://github.com/aweary/tinytime/blob/master/package.json#L5) but the source has flow type annotations, so that maybe isn't a good idea?

**Comment by ariamckinley** [comment]
That's probably it! For my projects I usually setup rollup to export a `.es.js` version alongside the other bundles. Not entirely sure how to set it up for webpack, but definitely a good idea. I'd love to use this lib! I am working with an extremely large web app where every little optimization matters. I wanted to benchmark this against our current date formatting methods 😄

**Comment by ariamckinley** [comment]
Oh wait, I see you're using rollup 😂  I got this confused with another lib I was checking out. I can try to resolve this if you haven't already
