### ISSUE TITLE
Feature request: zero-padded month

### ISSUE THREAD

**Issue by codepunkt** [aweary/tinytime#11]
A typical way to format dates in germany uses a zero-padded month.
Today, for example, is `23.04.2017`.
Zero-padded month would be a welcome addition!

**Comment by tarjei** [comment]
Use: 
`const template = tinytime('{Mo}', { padMonth: true })`

**Comment by pengfu** [comment]
Have you updated the npm package already?

**Comment by mistadikay** [comment]
@pengfu it's already implemented, just not documented

**Comment by aweary** [comment]
I added a note to the README about using this option, hope that helps!
