### ISSUE TITLE
Dates are being rendered one day behind

### ISSUE THREAD

**Issue by AndrewGardhouse** [aweary/tinytime#17]
I'm not sure what's going on or if anyone else is having a similar issue but dates are being formatted one day behind.

```
const template = tinytime('{MMMM} {Do}');

const aprilTwentyNinth = new Date("2017-04-29");
const aprilThirtieth = new Date("2017-04-30");
const mayFirst = new Date("2017-05-01");

console.log(template.render(aprilTwentyNinth)); // renders April 28th
console.log(template.render(aprilThirtieth)); // renders April 29th
console.log(template.render(mayFirst)); // renders April 30th
```

**Comment by aweary** [comment]
I believe it's because of your timezone. When you do `new Date('2017-4-29')` you're defaulting to midnight in GMT for 4/29. When it displays the date, it displays that date in your time. You'll want to be more specific about the time you wish to display.

For example:

```
new Date("2017-04-29 CST")
```
